name: Build museisfun.com

on:
  push:
    branches:
      - master
    paths:
      - 'app/**'
  pull_request:
    branches:
      - master
    paths:
      - 'app/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23.6.0'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install shared package dependencies
        working-directory: ./shared
        run: |
          bun install
          bun link
          bun run build

      - name: Install app dependencies
        run: bun install

      - name: Build app
        run: bun run build
