name: cloudflare image proxy tests

on:
  push:
    branches: [ master ]
    paths:
      - 'proxy/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'proxy/**'
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: proxy

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23.6.0'
          cache: 'npm'
          cache-dependency-path: 'proxy/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm test

      - name: Run integration tests
        run: npm run test:integration
