name: Build muse-shared package

on:
  push:
    branches:
      - master
    paths:
      - 'shared/**'
  pull_request:
    branches:
      - master
    paths:
      - 'shared/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./shared

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23.6.0'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Create symlink
        run: bun link

      - name: Install dependencies
        run: bun install

      - name: Build package
        run: bun run build
